services:
  - type: web
    name: balloon-backend
    env: python
    rootDir: app/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: static
    name: balloon-frontend
    rootDir: app/frontend
    buildCommand: pnpm install && pnpm build
    staticPublishPath: dist
