"""auto update

Revision ID: ad1f036477cd
Revises: b194af3516fd
Create Date: 2026-04-03 05:30:34.457007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1f036477cd'
down_revision: Union[str, Sequence[str], None] = 'b194af3516fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balloon_settings', sa.Column('logo_object_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balloon_settings', 'logo_object_key')
    # ### end Alembic commands ###