"""auto update

Revision ID: b194af3516fd
Revises: 
Create Date: 2026-04-02 13:49:04.817791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b194af3516fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balloon_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hourly_labor_rate', sa.Float(), nullable=False),
    sa.Column('overhead_percent', sa.Float(), nullable=False),
    sa.Column('markup_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balloon_settings_id'), 'balloon_settings', ['id'], unique=False)
    op.create_table('balloon_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('size_name', sa.String(), nullable=False),
    sa.Column('price_per_balloon', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balloon_sizes_id'), 'balloon_sizes', ['id'], unique=False)
    op.create_table('saved_designs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('design_name', sa.String(), nullable=False),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('hardware_cost', sa.Float(), nullable=True),
    sa.Column('overhead_percent', sa.Float(), nullable=True),
    sa.Column('markup_percent', sa.Float(), nullable=True),
    sa.Column('balloon_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('overhead_amount', sa.Float(), nullable=True),
    sa.Column('markup_amount', sa.Float(), nullable=True),
    sa.Column('msrp', sa.Float(), nullable=True),
    sa.Column('perceived_value_add', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('balloon_details', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_designs_id'), 'saved_designs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_designs_id'), table_name='saved_designs')
    op.drop_table('saved_designs')
    op.drop_index(op.f('ix_balloon_sizes_id'), table_name='balloon_sizes')
    op.drop_table('balloon_sizes')
    op.drop_index(op.f('ix_balloon_settings_id'), table_name='balloon_settings')
    op.drop_table('balloon_settings')
    # ### end Alembic commands ###